language: cpp
os: linux
dist: bionic
cache: ccache
git:
  depth: 1
before_script:
  - ccache -M 500M
script:
  - cd ${HOME}
  - git clone https://github.com/wloot/scripts 
  - sudo chmod -R +x scripts
  - sudo bash scripts/buildkernel.sh --clang
after_script:
  - sleep 1
